import type { Metadata } from "next";

import "./globals.css";
import Footer from "@/app/components/Footer/footer";
import localFont from 'next/font/local'
import Navbar from "@/app/components/Navbar/navbar";
import SmoothScrolling from "@/app/components/SmoothScrolling/smoothScrolling";
import CursorFollower from "@/app/components/CursorFollower/cursorFollower";
import { LanguageProvider } from "@/app/i18n/LanguageContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const hoves = localFont({
    src: [
        {
            path: './fonts/TT_Hoves_Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/TT_Hoves_Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-hoves'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang='pl' className={hoves.variable} suppressHydrationWarning>
          <body className="dark bg-background text-foreground">
              <LanguageProvider>
                  <SmoothScrolling>
                      <Navbar/>
                      {children}
                      <Footer/>
                  </SmoothScrolling>
              </LanguageProvider>
          </body>
      </html>
  );
}